# Generated by Django 4.0.6 on 2024-04-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('período', models.TextField(blank=True, db_column='Período', null=True)),
                ('polo', models.TextField(blank=True, db_column='Polo', null=True)),
                ('curso', models.TextField(blank=True, db_column='Curso', null=True)),
                ('eixo', models.TextField(blank=True, db_column='Eixo', null=True)),
                ('disciplina', models.TextField(blank=True, db_column='Disciplina', null=True)),
                ('turma', models.TextField(blank=True, db_column='Turma', null=True)),
                ('código_disciplina', models.TextField(blank=True, db_column='Código Disciplina', null=True)),
                ('código_prof_respons_field', models.TextField(blank=True, db_column='Código Prof. Respons.', null=True)),
                ('código_prof_videoaula', models.TextField(blank=True, db_column='Código Prof. Videoaula', null=True)),
            ],
            options={
                'db_table': 'cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Polos',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('polos', models.TextField(blank=True, null=True)),
                ('contato', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('num_vagas_eixo', models.TextField(blank=True, null=True)),
                ('total_vagas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'polos',
                'managed': False,
            },
        ),
    ]
